### ISSUE TITLE
Crash ao exportar

### ISSUE THREAD

**Issue by rodrigosiviero** [guimatheus92/SweetHome3D_HomeAssistant_Lightning#4]
Tentei usar mas ao apertar OK ele crasha o programa, não sei ao certo oque acontece pq nao indica nada. Outra coisa que pensei agora, talvez nao de pra fazer da casa inteira nesse metodo, nem to com todos grupos e ja esta gerando 260mil imagens, do jeito que eu tinha feito inicialemnte para o HA era literalmente recortar a area de cada lampada acesa e sobrepor na imagem original e nao gerar 1 imagem pra cada combinacao.
![2024-06-25 08_51_30-SIM Next](https://github.com/guimatheus92/SweetHome3D_HomeAssistant_Lightning/assets/4370989/6a689168-976c-440d-b744-47b6070d7f0f)
![2024-06-25 08_49_00-Information](https://github.com/guimatheus92/SweetHome3D_HomeAssistant_Lightning/assets/4370989/2b633cab-34be-41dc-98ef-cc633b37a53d)

Outra possibilidade é dividir a casa em quartos individuais, mas nao é a ideia do dashboard né

**Comment by guimatheus92** [comment]
> Tentei usar mas ao apertar OK ele crasha o programa, não sei ao certo oque acontece pq nao indica nada. Outra coisa que pensei agora, talvez nao de pra fazer da casa inteira nesse metodo, nem to com todos grupos e ja esta gerando 260mil imagens, do jeito que eu tinha feito inicialemnte para o HA era literalmente recortar a area de cada lampada acesa e sobrepor na imagem original e nao gerar 1 imagem pra cada combinacao. ![2024-06-25 08_51_30-SIM Next](https://private-user-images.githubusercontent.com/4370989/342715179-6a689168-976c-440d-b744-47b6070d7f0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzkyMDEsIm5iZiI6MTcxOTMzODkwMSwicGF0aCI6Ii80MzcwOTg5LzM0MjcxNTE3OS02YTY4OTE2OC05NzZjLTQ0MGQtYjc0NC00N2I2MDcwZDdmMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMTgwODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzczZWExNzMyY2YxOGY1ZmM5NDNmODNjOWJkYzk3NmRmZTAxYWUxMDdjYzRhMjJjOTRlMGVjZGQ3MTQ2NjZjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g44wqvszD27kbU0dbSMQwMmvYRfTGZ3BhUo0WW_2dXk) ![2024-06-25 08_49_00-Information](https://private-user-images.githubusercontent.com/4370989/342715237-2b633cab-34be-41dc-98ef-cc633b37a53d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzkyMDEsIm5iZiI6MTcxOTMzODkwMSwicGF0aCI6Ii80MzcwOTg5LzM0MjcxNTIzNy0yYjYzM2NhYi0zNGJlLTQxZGMtOThlZi1jYzYzM2IzN2E1M2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMTgwODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMwZDFhMzgwMmM2ODcxMzlkYTRhNzI0OWIzYzEzMDc4ODVlMzY3MTg4MTNmZjYyYjk1MjJjOWI0ZmFmYWIwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j5sJxeB3mR5zegx7R-keV5fhvedvRF0wZNnvdfIdIdE)
> 
> Outra possibilidade é dividir a casa em quartos individuais, mas nao é a ideia do dashboard né

Pra mim não crashou, mas também não está muito rapido a geração de imagem, então como o seu projeto tem muita coisa... aí pode ser que esteja dando problema mesmo. Eu to tentando pensar numa forma de gerar isso automaticamente de uma forma fácil e rapido. Consegui melhorar o que estava antes, mas longe do ideal ainda. Como que você fez no seu método 1 de "sobrepor" a imagem? Consegue mostrar um exemplo?

É, fazer por cômodos individuais acho que não seria o ideal não 😢

**Comment by guimatheus92** [comment]
@rodrigosiviero beleza? Encontrei um repo melhor que o meu e bem mais avançado. Está gerando as imagems certinho e com menor quantidade. Bem daquele jeito que conversamos, exportando por ambiente e por luz. Eu já estou dando manutenção lá também pra melhorar a qualidade: https://github.com/shmuelzon/home-assistant-floor-plan. Valeu pelo suporte!
